"""create content tables

Revision ID: ee99337b5d46
Revises: 0ca6b19935e1
Create Date: 2026-08-13 12:57:30.065159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee99337b5d46'
down_revision: Union[str, None] = '0ca6b19935e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'slug', name='uq_topic_domain_slug')
    )
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('concept_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('prerequisite', 'related', 'continues_with', name='relationship_type'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'type', name='uq_concept_relationship')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=True),
    sa.Column('como_funciona', sa.Text(), nullable=True),
    sa.Column('por_que_importa', sa.Text(), nullable=True),
    sa.Column('visualizacion', sa.Text(), nullable=True),
    sa.Column('ejemplo', sa.Text(), nullable=True),
    sa.Column('comandos', sa.Text(), nullable=True),
    sa.Column('errores_frecuentes', sa.Text(), nullable=True),
    sa.Column('regla_mental', sa.Text(), nullable=True),
    sa.Column('perspectiva_ofensiva', sa.Text(), nullable=True),
    sa.Column('perspectiva_defensiva', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('concept_relationships')
    op.drop_table('concepts')
    op.drop_table('topics')
    op.drop_table('domains')
    # ### end Alembic commands ###
