"""create notes tables

Revision ID: d4adafab9ec5
Revises: ee99337b5d46
Create Date: 2026-08-13 13:17:04.752095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4adafab9ec5'
down_revision: Union[str, None] = 'ee99337b5d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('linked_concept_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_notes_linked_concept_id', 'notes', ['linked_concept_id'], unique=True, postgresql_where=sa.text('linked_concept_id IS NOT NULL'))
    op.create_table('note_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_note_id', sa.UUID(), nullable=False),
    sa.Column('target_note_id', sa.UUID(), nullable=True),
    sa.Column('target_concept_id', sa.UUID(), nullable=True),
    sa.Column('link_text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_links')
    op.drop_index('uq_notes_linked_concept_id', table_name='notes', postgresql_where=sa.text('linked_concept_id IS NOT NULL'))
    op.drop_table('notes')
    # ### end Alembic commands ###
