"""create mastery tables

Revision ID: 17635b8c9f76
Revises: 98dd13b72b34
Create Date: 2026-08-13 13:54:14.464855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17635b8c9f76'
down_revision: Union[str, None] = '98dd13b72b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_masteries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tested', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_concept_mastery_user_concept')
    )
    op.create_table('review_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_mastery_id', sa.UUID(), nullable=False),
    sa.Column('stability_days', sa.Float(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_mastery_id'], ['concept_masteries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_mastery_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_schedules')
    op.drop_table('concept_masteries')
    # ### end Alembic commands ###
