"""create review tables

Revision ID: 368f6e25f45b
Revises: 17635b8c9f76
Create Date: 2026-08-13 13:54:56.032508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368f6e25f45b'
down_revision: Union[str, None] = '17635b8c9f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_session_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('question_variant_id', sa.UUID(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('confidence_declared', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.Enum('correct', 'partial', 'incorrect', name='review_outcome'), nullable=True),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_items')
    op.drop_table('review_sessions')
    # ### end Alembic commands ###
