"""create focus tables

Revision ID: 33d9b299eb17
Revises: 368f6e25f45b
Create Date: 2026-08-13 14:46:30.808707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d9b299eb17'
down_revision: Union[str, None] = '368f6e25f45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_time_sec', sa.Integer(), nullable=False),
    sa.Column('last_position', sa.String(length=255), nullable=True),
    sa.Column('timer_mode', sa.Enum('count_up', 'pomodoro', 'countdown', 'no_timer', name='timer_mode'), nullable=False),
    sa.Column('pomodoro_preset', sa.String(length=16), nullable=True),
    sa.Column('break_reminder_threshold_min', sa.Integer(), nullable=False),
    sa.Column('hyperfocus_reminder_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
