"""create lab tables

Revision ID: 30f615008e5c
Revises: 33d9b299eb17
Create Date: 2026-08-13 18:36:43.444929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f615008e5c'
down_revision: Union[str, None] = '33d9b299eb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('duration_estimate_min', sa.Integer(), nullable=False),
    sa.Column('docker_build_context', sa.String(length=255), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('cpu_limit', sa.String(length=16), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('max_lifetime_min', sa.Integer(), nullable=False),
    sa.Column('cleanup_remove_volumes', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('laboratory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'provisioning', 'running', 'stopped', 'destroyed', 'expired', 'failed', name='lab_instance_status'), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('network_id', sa.String(length=64), nullable=True),
    sa.Column('host_port', sa.Integer(), nullable=True),
    sa.Column('context_seed', sa.JSON(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_concepts',
    sa.Column('laboratory_id', sa.String(length=64), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('laboratory_id', 'concept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory_concepts')
    op.drop_table('lab_instances')
    op.drop_table('laboratories')
    # ### end Alembic commands ###
