"""add relay_pid to lab_instances

Revision ID: add41ccee7a5
Revises: 30f615008e5c
Create Date: 2026-08-13 18:45:02.513320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add41ccee7a5'
down_revision: Union[str, None] = '30f615008e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_instances', sa.Column('relay_pid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_instances', 'relay_pid')
    # ### end Alembic commands ###
